sudo: required
services:
  - docker

before_install:
  - docker build -t kobilee/docker-react -f Dockerfile.dev . 

script:
  - docker run kobilee/docker-react npm run test -- --coverage

deploy:
  provider: elsticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-723167900301"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"